spring:
  application:
    name: deblur
  #  thymeleaf:
  #    mode: HTML5
  #    encoding: UTF-8
  #    servlet:
  #      content-type: text/html
  #    cache: false
  resources:
    static-locations: file:/stdStorage/taozi/deblur_sys/img/
  redis:
    host: 202.115.17.206
    port: 6479
    password: 9981
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000

server:
  port: 8081
  imgServerPath: /stdStorage/taozi/deblur_sys/img/
  shServerPath: /stdStorage/taozi/deblur_sys/src/main/java/com/taozi/deblur/util/
  imgTomcatPath: http://202.115.17.206:${server.port}/dataset/motion/

centos:
  ip: 202.115.17.206
  name: tzx
  password: 123
  port: 9977
